spring:
  application.name: video_storage_backend
  servlet.multipart:
    max-file-size: 10MB
    max-request-size: 10MB

  jpa:
    hibernate.ddl-auto: none

activity-detector:
  video:
    folderPath: ${VIDEO_FOLDER_PATH:videos} #Sciezka wzieta ze zmiennej srodowiskowej lub jezeli jej nie ma domyslna wartosc videos
    subfolderDepth: 1 #Liczba poziomów subfolderów w katalogu z video. 0 oznacza brak subfolderow w katalogu.

  detected-elements:
    - human
    - knife
    - backpack

springdoc.api-docs.enabled: true
springdoc.swagger-ui.enabled: false
springdoc:
  default-operation-id-generation-mode: method

server.forward-headers-strategy: framework
